### PR TITLE
add 1440p/1080p ultrawide support

### PR DESCRIPTION
**Pull request by FearrMe**
game doesn't support ultrawide as far as i'm aware, so it's black bars.
not tested but should work simply by adding an offset for the black bars (3440-2560)/2 = 440 (2560-1080)/2 = 320

https://i.imgur.com/5PN1UVq.png full screenshot for confirmation

### CODE REVIEW

**Comment by FearrMe** [comment]
I was a bit wrong, ETT does support ultrawide but it doesn't rescale anything so it should still work (https://i.imgur.com/SLSdTra.png to compare)

**Comment by jerryfromearth** [comment]
Hi @FearrMe , thanks for the PR. 
Have you tested the two new resolutions to make sure the script still works?

**Comment by FearrMe** [comment]
Yeah, it works (as far as a macro like this goes :P). Probably worth changing the mouse offscreen position to `2560,1080` and `3440,1440` for consistency.

**Comment by jerryfromearth** [comment]
Excellent. I'll merge it tonight.

**Pull request merged**
